[package]
name = "smolpuff"
version = "0.1.0"
edition = "2024"

[dependencies]
object_store = { version = "0.12.4", features = ["gcp", "azure"] }
slatedb = { version = "0.9.2", default-features = false }
tokio = { version = "1.48.0", features = ["macros"] }
